"""
gem_api.py

NOTE: In the Modal architecture, FastAPI is NOT a separate script.
The web endpoint IS defined in gem_pipeline.py via @modal.web_endpoint.

This file documents the available endpoints and how to call them.

Endpoints (auto-generated by Modal — get URLs after: modal deploy gem_pipeline.py):
─────────────────────────────────────────────────────────────────────────────
POST https://<your-workspace>--gem-ask.modal.run
     Body: AskRequest JSON
     Returns: AskResponse JSON

GET  https://<your-workspace>--gem-health.modal.run
     Returns: health status JSON

How to get your URLs:
─────────────────────────────────────────────────────────────────────────────
    modal deploy gem_pipeline.py

Output will show:
    ✅ Created web endpoint gem-ask  → https://yourname--gem-ask.modal.run
    ✅ Created web endpoint gem-health → https://yourname--gem-health.modal.run

Copy those URLs into gem_streamlit.py as MODAL_ASK_URL and MODAL_HEALTH_URL.
"""

# ── Request/Response schemas (reference) ─────────────────────────────────

ASK_REQUEST_SCHEMA = {
    "question":        "string (required) — your question in AR or EN",
    "top_k":           "int (default: 5) — chunks to retrieve",
    "score_threshold": "float (default: 0.45) — min similarity score",
    "language_filter": "string | null — 'ar' | 'en' | null",
    "category_filter": "string | null — 'collection' | 'visitor_info' | ...",
    "chat_history":    "string (default: '') — formatted previous turns",
}

ASK_RESPONSE_SCHEMA = {
    "question":         "string",
    "answer":           "string",
    "sources":          "list of {title, url, category, language, score}",
    "query_type":       "string — 'general' | 'history' | 'visitor_info'",
    "query_language":   "string — 'ar' | 'en'",
    "chunks_retrieved": "int",
}

# ── Example curl call ─────────────────────────────────────────────────────
EXAMPLE_CURL = """
curl -X POST https://yourname--gem-ask.modal.run \\
  -H "Content-Type: application/json" \\
  -d '{
    "question": "What are the opening hours?",
    "top_k": 5
  }'
"""

# ── Example Python call ───────────────────────────────────────────────────
EXAMPLE_PYTHON = """
import requests

MODAL_URL = "https://yourname--gem-ask.modal.run"

response = requests.post(MODAL_URL, json={
    "question": "Tell me about Tutankhamun",
    "top_k": 5,
})

data = response.json()
print(data["answer"])
print(data["sources"])
"""